import {z} from 'zod'; import User from '../models/User.js'; import {Department,Division,Subject,StudentProfile,FacultyProfile,FacultyAssignment} from '../models/Academic.js'; import {AttendanceSession,AttendanceRecord,CorrectionRequest} from '../models/Attendance.js';
const departmentSchema=z.object({name:z.string().min(2).max(100),code:z.string().min(2).max(12).transform(x=>x.toUpperCase())});
export async function overview(req,res,next){try{const [students,faculty,departments,sessions,records]=await Promise.all([StudentProfile.countDocuments(),FacultyProfile.countDocuments(),Department.countDocuments(),AttendanceSession.countDocuments({status:'submitted'}),AttendanceRecord.find().select('status')]);const eligible=records.length,attended=records.filter(r=>['present','late','excused'].includes(r.status)).length;res.json({students,faculty,departments,sessions,average:eligible?Math.round(attended/eligible*100):0})}catch(e){next(e)}}
export async function listAcademics(req,res,next){try{const [departments,divisions,subjects]=await Promise.all([Department.find().sort('name'),Division.find().populate('department','name code').sort('semester name'),Subject.find().populate('department','name code').sort('code')]);res.json({departments,divisions,subjects})}catch(e){next(e)}}
export async function createDepartment(req,res,next){try{const department=await Department.create(departmentSchema.parse(req.body));res.status(201).json({department})}catch(e){next(e)}}
export async function people(req,res,next){try{const [students,faculty]=await Promise.all([StudentProfile.find().populate('user','name email').populate('division','name semester').sort('rollNumber'),FacultyProfile.find().populate('user','name email').populate('department','name code').sort('employeeId')]);res.json({students,faculty})}catch(e){next(e)}}
export async function governance(req,res,next){try{const [sessions,requests]=await Promise.all([AttendanceSession.find().populate('subject division faculty').sort('-submittedAt').limit(30),CorrectionRequest.find().populate({path:'student',populate:{path:'user',select:'name'}}).sort('-createdAt')]);res.json({sessions,requests})}catch(e){next(e)}}
const subjectSchema=z.object({name:z.string().min(2),code:z.string().min(2).max(12),department:z.string(),semester:z.coerce.number().int().min(1).max(8)});const assignmentSchema=z.object({faculty:z.string(),subject:z.string(),division:z.string()});
export async function createSubject(req,res,next){try{const subject=await Subject.create(subjectSchema.parse(req.body));res.status(201).json({subject})}catch(e){next(e)}}
export async function assignFaculty(req,res,next){try{const assignment=await FacultyAssignment.create(assignmentSchema.parse(req.body));res.status(201).json({assignment})}catch(e){next(e)}}
export async function removePerson(req,res,next){try{const profile=req.params.type==='student'?await StudentProfile.findById(req.params.id):await FacultyProfile.findById(req.params.id);if(!profile)return res.status(404).json({message:'Person not found'});if(req.params.type==='faculty')await FacultyAssignment.deleteMany({faculty:profile._id});await User.findByIdAndDelete(profile.user);await profile.deleteOne();res.json({message:'Account removed'})}catch(e){next(e)}}
